name: Generate Documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          sudo apt install plantuml doxygen cmake
          pip install sphinx sphinx_rtd_theme myst_parser sphinxcontrib-plantuml sphinxcontrib-apidoc sphinx-needs pillow sphinx-epytext breathe myst-parser
      - name: Generate documentation for Proto
        run: |
          cd CatCutifier
          cmake .
          cmake --build .
          doxygen
      - name: Generate documentation for C++
        run: |
          docker run --rm   -v $(pwd)/docs/_build/proto:/out   -v $(pwd)/proto:/protos   pseudomuto/protoc-gen-doc --doc_opt=markdown,docs.md
          sudo chown $USER $(pwd)/docs/_build/proto/docs.md
      - name: Sphinx build
        run: |
          sphinx-build docs _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true